// Liste exhaustive des filières scolaires et professionnelles en France
// Organisées par catégories pour faciliter la navigation

export interface Filiere {
  value: string
  label: string
  category: string
  description?: string
}

export const CATEGORIES = [
  { id: 'college', label: 'Collège', icon: '🏫' },
  { id: 'lycee_general', label: 'Lycée Général', icon: '📚' },
  { id: 'lycee_techno', label: 'Lycée Technologique', icon: '🔧' },
  { id: 'lycee_pro', label: 'Lycée Professionnel', icon: '🛠️' },
  { id: 'superieur_court', label: 'Enseignement Supérieur Court', icon: '🎓' },
  { id: 'superieur_long', label: 'Enseignement Supérieur Long', icon: '🏆' },
  { id: 'apprentissage', label: 'Apprentissage', icon: '⚙️' },
  { id: 'formation_continue', label: 'Formation Continue', icon: '💼' },
] as const

export const FILIERES: Filiere[] = [
  // COLLÈGE
  { value: '6eme', label: '6ème', category: 'college', description: 'Première année du cycle 3' },
  { value: '5eme', label: '5ème', category: 'college', description: 'Deuxième année du cycle 3' },
  { value: '4eme', label: '4ème', category: 'college', description: 'Première année du cycle 4' },
  { value: '3eme', label: '3ème', category: 'college', description: 'Année du brevet' },
  { value: '3eme_prepa_metiers', label: '3ème Prépa-Métiers', category: 'college', description: 'Découverte des métiers' },

  // LYCÉE GÉNÉRAL
  { value: 'seconde_generale', label: 'Seconde Générale', category: 'lycee_general', description: 'Cycle de détermination' },
  { value: 'premiere_generale', label: 'Première Générale', category: 'lycee_general', description: 'Première année du cycle terminal' },
  { value: 'terminale_generale', label: 'Terminale Générale', category: 'lycee_general', description: 'Année du baccalauréat' },
  
  // Spécialités du bac général
  { value: 'bac_specialite_math', label: 'Spécialité Mathématiques', category: 'lycee_general' },
  { value: 'bac_specialite_nsi', label: 'Spécialité NSI', category: 'lycee_general', description: 'Numérique et Sciences Informatiques' },
  { value: 'bac_specialite_physique', label: 'Spécialité Physique-Chimie', category: 'lycee_general' },
  { value: 'bac_specialite_svt', label: 'Spécialité SVT', category: 'lycee_general', description: 'Sciences de la Vie et de la Terre' },
  { value: 'bac_specialite_hggsp', label: 'Spécialité HGGSP', category: 'lycee_general', description: 'Histoire-Géographie, Géopolitique et Sciences Politiques' },
  { value: 'bac_specialite_hlp', label: 'Spécialité HLP', category: 'lycee_general', description: 'Humanités, Littérature et Philosophie' },
  { value: 'bac_specialite_anglais', label: 'Spécialité LLCE Anglais', category: 'lycee_general', description: 'Langues, Littératures et Cultures Étrangères' },
  { value: 'bac_specialite_allemand', label: 'Spécialité LLCE Allemand', category: 'lycee_general' },
  { value: 'bac_specialite_espagnol', label: 'Spécialité LLCE Espagnol', category: 'lycee_general' },
  { value: 'bac_specialite_ses', label: 'Spécialité SES', category: 'lycee_general', description: 'Sciences Économiques et Sociales' },
  { value: 'bac_specialite_biologie', label: 'Spécialité Biologie-Écologie', category: 'lycee_general' },
  { value: 'bac_specialite_geopolitique', label: 'Spécialité Géopolitique', category: 'lycee_general' },
  { value: 'bac_specialite_arts', label: 'Spécialité Arts', category: 'lycee_general' },
  { value: 'bac_specialite_musique', label: 'Spécialité Musique', category: 'lycee_general' },
  { value: 'bac_specialite_theatre', label: 'Spécialité Théâtre', category: 'lycee_general' },
  { value: 'bac_specialite_danse', label: 'Spécialité Danse', category: 'lycee_general' },
  { value: 'bac_specialite_arts_plastiques', label: 'Spécialité Arts Plastiques', category: 'lycee_general' },
  { value: 'bac_specialite_cinema', label: 'Spécialité Cinéma-Audiovisuel', category: 'lycee_general' },
  { value: 'bac_specialite_lca', label: 'Spécialité LCA', category: 'lycee_general', description: 'Langues et Cultures de l\'Antiquité' },
  { value: 'bac_specialite_droit', label: 'Spécialité Droit et Grands Enjeux', category: 'lycee_general' },
  { value: 'bac_specialite_maths_complet', label: 'Spécialité Mathématiques Expertes', category: 'lycee_general' },
  { value: 'bac_option_latin', label: 'Option Latin', category: 'lycee_general' },
  { value: 'bac_option_grec', label: 'Option Grec', category: 'lycee_general' },

  // LYCÉE TECHNOLOGIQUE
  { value: 'bac_stmg', label: 'Bac STMG', category: 'lycee_techno', description: 'Sciences et Technologies du Management et de la Gestion' },
  { value: 'bac_sti2d', label: 'Bac STI2D', category: 'lycee_techno', description: 'Sciences et Technologies de l\'Industrie et du Développement Durable' },
  { value: 'bac_std2a', label: 'Bac STD2A', category: 'lycee_techno', description: 'Sciences et Technologies du Design et des Arts Appliqués' },
  { value: 'bac_stl', label: 'Bac STL', category: 'lycee_techno', description: 'Sciences et Technologies de Laboratoire' },
  { value: 'bac_st2s', label: 'Bac ST2S', category: 'lycee_techno', description: 'Sciences et Technologies de la Santé et du Social' },
  { value: 'bac_stav', label: 'Bac STAV', category: 'lycee_techno', description: 'Sciences et Technologies de l\'Agronomie et du Vivant' },
  { value: 'bac_tmd', label: 'Bac TMD', category: 'lycee_techno', description: 'Techniques de la Musique et de la Danse' },
  { value: 'bac_hest', label: 'Bac Hôtellerie', category: 'lycee_techno', description: 'Hôtellerie et Restauration' },

  // LYCÉE PROFESSIONNEL - CAP (Certificat d'Aptitude Professionnelle)
  { value: 'cap_commerce', label: 'CAP Commerce', category: 'lycee_pro', description: 'Vente, prospection' },
  { value: 'cap_cuisine', label: 'CAP Cuisine', category: 'lycee_pro' },
  { value: 'cap_patisserie', label: 'CAP Pâtisserie', category: 'lycee_pro' },
  { value: 'cap_boulangerie', label: 'CAP Boulangerie', category: 'lycee_pro' },
  { value: 'cap_boucherie', label: 'CAP Boucherie', category: 'lycee_pro' },
  { value: 'cap_charcuterie', label: 'CAP Charcuterie-Traiteur', category: 'lycee_pro' },
  { value: 'cap_coiffure', label: 'CAP Coiffure', category: 'lycee_pro' },
  { value: 'cap_esthetique', label: 'CAP Esthétique Cosmétique Parfumerie', category: 'lycee_pro' },
  { value: 'cap_electricien', label: 'CAP Électricien', category: 'lycee_pro' },
  { value: 'cap_plombier', label: 'CAP Plombier', category: 'lycee_pro' },
  { value: 'cap_menuisier', label: 'CAP Menuisier', category: 'lycee_pro' },
  { value: 'cap_macon', label: 'CAP Maçon', category: 'lycee_pro' },
  { value: 'cap_peintre', label: 'CAP Peintre', category: 'lycee_pro' },
  { value: 'cap_mecanicien', label: 'CAP Mécanicien', category: 'lycee_pro' },
  { value: 'cap_carrossier', label: 'CAP Carrossier', category: 'lycee_pro' },
  { value: 'cap_agriculture', label: 'CAP Agricole', category: 'lycee_pro' },
  { value: 'cap_soins_animaux', label: 'CAP Soins aux Animaux', category: 'lycee_pro' },
  { value: 'cap_petite_enfance', label: 'CAP Accompagnant Éducatif Petite Enfance', category: 'lycee_pro' },
  { value: 'cap_aide_personnes', label: 'CAP Accompagnement au Grand Âge', category: 'lycee_pro' },
  { value: 'cap_serrurier', label: 'CAP Serrurier Métallier', category: 'lycee_pro' },
  { value: 'cap_tailleur', label: 'CAP Tailleur de Pierre', category: 'lycee_pro' },
  { value: 'cap_fleuriste', label: 'CAP Fleuriste', category: 'lycee_pro' },
  { value: 'cap_jardinier', label: 'CAP Jardinier Paysagiste', category: 'lycee_pro' },
  { value: 'cap_imprimerie', label: 'CAP Imprimerie', category: 'lycee_pro' },
  { value: 'cap_graphisme', label: 'CAP Graphiste', category: 'lycee_pro' },
  { value: 'cap_horticulture', label: 'CAP Horticulture', category: 'lycee_pro' },
  { value: 'cap_viticulture', label: 'CAP Viticulture', category: 'lycee_pro' },
  { value: 'cap_maroquinerie', label: 'CAP Maroquinerie', category: 'lycee_pro' },
  { value: 'cap_tapissier', label: 'CAP Tapissier', category: 'lycee_pro' },
  { value: 'cap_cordonnerie', label: 'CAP Cordonnerie', category: 'lycee_pro' },
  { value: 'cap_bijouterie', label: 'CAP Bijouterie-Joaillerie', category: 'lycee_pro' },
  { value: 'cap_verrerie', label: 'CAP Verrerie', category: 'lycee_pro' },
  { value: 'cap_ceramique', label: 'CAP Céramique', category: 'lycee_pro' },
  { value: 'cap_ebeniste', label: 'CAP Ébéniste', category: 'lycee_pro' },
  { value: 'cap_charpentier', label: 'CAP Charpentier', category: 'lycee_pro' },
  { value: 'cap_couvreur', label: 'CAP Couvreur', category: 'lycee_pro' },
  { value: 'cap_plaquiste', label: 'CAP Plaquiste', category: 'lycee_pro' },
  { value: 'cap_solier', label: 'CAP Solier-Moquetiste', category: 'lycee_pro' },
  { value: 'cap_froid', label: 'CAP Froid et Conditionnement d\'Air', category: 'lycee_pro' },
  { value: 'cap_chauffage', label: 'CAP Chauffage', category: 'lycee_pro' },
  { value: 'cap_soudure', label: 'CAP Soudure', category: 'lycee_pro' },
  { value: 'cap_usinage', label: 'CAP Usinage', category: 'lycee_pro' },
  { value: 'cap_outillage', label: 'CAP Outillage', category: 'lycee_pro' },
  { value: 'cap_maintenance', label: 'CAP Maintenance des Véhicules', category: 'lycee_pro' },
  { value: 'cap_agroalimentaire', label: 'CAP Agroalimentaire', category: 'lycee_pro' },
  { value: 'cap_bordeaux', label: 'CAP Sommellerie', category: 'lycee_pro' },
  { value: 'cap_fromager', label: 'CAP Fromager', category: 'lycee_pro' },
  { value: 'cap_chocolatier', label: 'CAP Chocolatier-Confiseur', category: 'lycee_pro' },
  { value: 'cap_glacier', label: 'CAP Glacier', category: 'lycee_pro' },
  { value: 'cap_poissonnier', label: 'CAP Poissonnier-Écailler', category: 'lycee_pro' },
  { value: 'cap_caviste', label: 'CAP Caviste', category: 'lycee_pro' },
  { value: 'cap_cyclisme', label: 'CAP Cycle', category: 'lycee_pro' },
  { value: 'cap_sellerie', label: 'CAP Sellerie', category: 'lycee_pro' },
  { value: 'cap_nautisme', label: 'CAP Nautisme', category: 'lycee_pro' },
  { value: 'cap_amateur', label: 'CAP Aménagement et Finition', category: 'lycee_pro' },

  // BACS PROFESSIONNELS
  { value: 'bac_pro_commerce', label: 'Bac Pro Commerce', category: 'lycee_pro' },
  { value: 'bac_pro_vente', label: 'Bac Pro Métiers du Commerce et de la Vente', category: 'lycee_pro' },
  { value: 'bac_pro_gestion_admin', label: 'Bac Pro Gestion-Administration', category: 'lycee_pro' },
  { value: 'bac_pro_assp', label: 'Bac Pro ASSP', category: 'lycee_pro', description: 'Accompagnement Soins et Services à la Personne' },
  { value: 'bac_pro_aepa', label: 'Bac Pro AEPA', category: 'lycee_pro', description: 'Accompagnement Éducatif Petite Enfance' },
  { value: 'bac_pro_hotellerie', label: 'Bac Pro Hôtellerie', category: 'lycee_pro' },
  { value: 'bac_pro_restaurateur', label: 'Bac Pro Restaurateur', category: 'lycee_pro' },
  { value: 'bac_pro_cuisine', label: 'Bac Pro Cuisine', category: 'lycee_pro' },
  { value: 'bac_pro_boulangerie', label: 'Bac Pro Boulangerie-Pâtisserie', category: 'lycee_pro' },
  { value: 'bac_pro_boucherie', label: 'Bac Pro Boucherie-Charcuterie', category: 'lycee_pro' },
  { value: 'bac_pro_coiffure', label: 'Bac Pro Coiffure', category: 'lycee_pro' },
  { value: 'bac_pro_esthetique', label: 'Bac Pro Esthétique-Cosmétique-Parfumerie', category: 'lycee_pro' },
  { value: 'bac_pro_electrotechnique', label: 'Bac Pro Électrotechnique', category: 'lycee_pro', description: 'Énergie Équipements Communicants' },
  { value: 'bac_pro_energies', label: 'Bac Pro Systèmes Énergétiques et Climatiques', category: 'lycee_pro' },
  { value: 'bac_pro_numerique', label: 'Bac Pro Systèmes Numériques', category: 'lycee_pro' },
  { value: 'bac_pro_melec', label: 'Bac Pro MELEC', category: 'lycee_pro', description: 'Métiers de l\'Électricité et de ses Environnements Connectés' },
  { value: 'bac_pro_tci', label: 'Bac Pro TCI', category: 'lycee_pro', description: 'Technicien Constructeur Industriel' },
  { value: 'bac_pro_tu', label: 'Bac Pro TU', category: 'lycee_pro', description: 'Technicien d\'Usinage' },
  { value: 'bac_pro_maintenance', label: 'Bac Pro Maintenance des Équipements Industriels', category: 'lycee_pro' },
  { value: 'bac_pro_aeronautique', label: 'Bac Pro Aéronautique', category: 'lycee_pro' },
  { value: 'bac_pro_automobile', label: 'Bac Pro Maintenance des Véhicules', category: 'lycee_pro' },
  { value: 'bac_pro_agora', label: 'Bac Pro AGOrA', category: 'lycee_pro', description: 'Assistance à la Gestion des Organisations et de leurs Activités' },
  { value: 'bac_pro_logistique', label: 'Bac Pro Logistique', category: 'lycee_pro' },
  { value: 'bac_pro_transports', label: 'Bac Pro Transports et Prestations Logistiques', category: 'lycee_pro' },
  { value: 'bac_pro_batiment', label: 'Bac Pro Bâtiment', category: 'lycee_pro' },
  { value: 'bac_pro_gros_oeuvre', label: 'Bac Pro Gros Œuvre du Bâtiment', category: 'lycee_pro' },
  { value: 'bac_pro_finition', label: 'Bac Pro Finition du Bâtiment', category: 'lycee_pro' },
  { value: 'bac_pro_amenagement', label: 'Bac Pro Aménagement et Finition du Bâtiment', category: 'lycee_pro' },
  { value: 'bac_pro_agriculture', label: 'Bac Pro Agri-Environnement', category: 'lycee_pro' },
  { value: 'bac_pro_cgea', label: 'Bac Pro CGEA', category: 'lycee_pro', description: 'Conduite et Gestion de l\'Exploitation Agricole' },
  { value: 'bac_pro_forêt', label: 'Bac Pro Forêt', category: 'lycee_pro' },
  { value: 'bac_pro_paysage', label: 'Bac Pro Jardins et Paysages', category: 'lycee_pro' },
  { value: 'bac_pro_viticole', label: 'Bac Pro Viticulture-Œnologie', category: 'lycee_pro' },
  { value: 'bac_pro_animaux', label: 'Bac Pro Animateur-Naturaliste', category: 'lycee_pro' },
  { value: 'bac_pro_sapat', label: 'Bac Pro SAPAT', category: 'lycee_pro', description: 'Services Aux Personnes et Aux Territoires' },
  { value: 'bac_pro_optique', label: 'Bac Pro Optique-Lunetterie', category: 'lycee_pro' },
  { value: 'bac_pro_audiovisuel', label: 'Bac Pro Audiovisuel', category: 'lycee_pro' },
  { value: 'bac_pro_graphisme', label: 'Bac Pro Graphisme', category: 'lycee_pro' },
  { value: 'bac_pro_mode', label: 'Bac Pro Mode et Vêtements', category: 'lycee_pro' },
  { value: 'bac_pro_cuirs', label: 'Bac Pro Métiers du Cuir et de la Maroquinerie', category: 'lycee_pro' },
  { value: 'bac_pro_verre', label: 'Bac Pro Métiers du Verre', category: 'lycee_pro' },
  { value: 'bac_pro_ceramique', label: 'Bac Pro Céramique', category: 'lycee_pro' },
  { value: 'bac_pro_materiaux', label: 'Bac Pro Matériaux Laboratoire', category: 'lycee_pro' },
  { value: 'bac_pro_chimie', label: 'Bac Pro Procédés de la Chimie', category: 'lycee_pro' },
  { value: 'bac_pro_bio', label: 'Bac Pro Biotechnologies', category: 'lycee_pro' },
  { value: 'bac_pro_pharmaceutique', label: 'Bac Pro Technicien Pharmaceutique', category: 'lycee_pro' },
  { value: 'bac_pro_sante', label: 'Bac Pro Prévention et Sécurité Sanitaire', category: 'lycee_pro' },
  { value: 'bac_pro_securite', label: 'Bac Pro Métiers de la Sécurité', category: 'lycee_pro' },
  { value: 'bac_pro_ciel', label: 'Bac Pro CIEL', category: 'lycee_pro', description: 'Cybersécurité, Informatique et Électronique' },
  { value: 'bac_pro_tica', label: 'Bac Pro TICA', category: 'lycee_pro', description: 'Technicien Installation des Systèmes Énergétiques et Climatiques' },
  { value: 'bac_pro_artisanat', label: 'Bac Pro Artisanat et Métiers d\'Art', category: 'lycee_pro' },
  { value: 'bac_pro_musique', label: 'Bac Pro Musiques Actuelles Amplifiées', category: 'lycee_pro' },
  { value: 'bac_pro_danse', label: 'Bac Pro Danse', category: 'lycee_pro' },
  { value: 'bac_pro_arts_du_cirque', label: 'Bac Pro Arts du Cirque', category: 'lycee_pro' },
  { value: 'bac_pro_pilote', label: 'Bac Pro Transport Fluvial', category: 'lycee_pro' },
  { value: 'bac_pro_nautisme', label: 'Bac Pro Nautisme', category: 'lycee_pro' },
  { value: 'bac_pro_aquaculture', label: 'Bac Pro Aquaculture', category: 'lycee_pro' },
  { value: 'bac_pro_pêche', label: 'Bac Pro Pêche et Gestion de l\'Environnement Marin', category: 'lycee_pro' },
  { value: 'bac_pro_agroalimentaire', label: 'Bac Pro Agroalimentaire', category: 'lycee_pro' },
  { value: 'bac_pro_boulangerie_rechauffe', label: 'Bac Pro Boulangerie-Pâtisserie', category: 'lycee_pro' },
  { value: 'bac_pro_charcuterie', label: 'Bac Pro Charcuterie-Traiteur', category: 'lycee_pro' },
  { value: 'bac_pro_glacerie', label: 'Bac Pro Glacerie', category: 'lycee_pro' },
  { value: 'bac_pro_tapissier', label: 'Bac Pro Tapisserie', category: 'lycee_pro' },
  { value: 'bac_pro_ébénisterie', label: 'Bac Pro Ébénisterie', category: 'lycee_pro' },
  { value: 'bac_pro_lutherie', label: 'Bac Pro Lutherie', category: 'lycee_pro' },
  { value: 'bac_pro_orfèvrerie', label: 'Bac Pro Orfèvrerie', category: 'lycee_pro' },
  { value: 'bac_pro_joaillerie', label: 'Bac Pro Joaillerie', category: 'lycee_pro' },
  { value: 'bac_pro_verrier', label: 'Bac Pro Verrier', category: 'lycee_pro' },
  { value: 'bac_pro_couture', label: 'Bac Pro Couture Floue', category: 'lycee_pro' },
  { value: 'bac_pro_dorure', label: 'Bac Pro Dorure', category: 'lycee_pro' },
  { value: 'bac_pro_encadrement', label: 'Bac Pro Encadrement', category: 'lycee_pro' },
  { value: 'bac_pro_reliure', label: 'Bac Pro Reliure et Restauration de Livres', category: 'lycee_pro' },
  { value: 'bac_pro_gravure', label: 'Bac Pro Gravure', category: 'lycee_pro' },
  { value: 'bac_pro_mosaïque', label: 'Bac Pro Mosaïque', category: 'lycee_pro' },
  { value: 'bac_pro_sculpture', label: 'Bac Pro Sculpture', category: 'lycee_pro' },
  { value: 'bac_pro_costume', label: 'Bac Pro Costumes du Spectacle', category: 'lycee_pro' },
  { value: 'bac_pro_régie', label: 'Bac Pro Régie du Spectacle', category: 'lycee_pro' },
  { value: 'bac_pro_armurerie', label: 'Bac Pro Armurerie', category: 'lycee_pro' },

  // BTS - BREVET DE TECHNICIEN SUPÉRIEUR
  { value: 'bts_mco', label: 'BTS MCO', category: 'superieur_court', description: 'Management Commercial Opérationnel (ex BTS Vente)' },
  { value: 'bts_sio', label: 'BTS SIO', category: 'superieur_court', description: 'Services Informatiques aux Organisations' },
  { value: 'bts_cg', label: 'BTS CG', category: 'superieur_court', description: 'Comptabilité et Gestion' },
  { value: 'bts_gest', label: 'BTS Gestion de la PME', category: 'superieur_court' },
  { value: 'bts_ndrc', label: 'BTS NDRC', category: 'superieur_court', description: 'Négociation et Digitalisation de la Relation Client' },
  { value: 'bts_sam', label: 'BTS SAM', category: 'superieur_court', description: 'Support à l\'Action Managériale' },
  { value: 'bts_tourisme', label: 'BTS Tourisme', category: 'superieur_court' },
  { value: 'bts_hotellerie', label: 'BTS Hôtellerie-Restauration', category: 'superieur_court' },
  { value: 'bts_ciro', label: 'BTS CI', category: 'superieur_court', description: 'Contrôle Industriel et Régulation Automatique' },
  { value: 'bts_crsa', label: 'BTS CRSA', category: 'superieur_court', description: 'Conception et Réalisation de Systèmes Automatiques' },
  { value: 'bts_electrotechnique', label: 'BTS Électrotechnique', category: 'superieur_court' },
  { value: 'bts_energy', label: 'BTS Fluides Énergies Environnement', category: 'superieur_court' },
  { value: 'bts_maintenance', label: 'BTS Maintenance Industrielle', category: 'superieur_court' },
  { value: 'bts_cprp', label: 'BTS CPRP', category: 'superieur_court', description: 'Conception des Processus de Réalisation de Produits' },
  { value: 'bts_construction', label: 'BTS Bâtiment', category: 'superieur_court' },
  { value: 'bts_tp', label: 'BTS Travaux Publics', category: 'superieur_court' },
  { value: 'bts_agro', label: 'BTS Agroéquipements', category: 'superieur_court' },
  { value: 'bts_acse', label: 'BTS ACSE', category: 'superieur_court', description: 'Analyse et Conception des Systèmes Énergétiques' },
  { value: 'bts_bio', label: 'BTS Biotechnologies', category: 'superieur_court' },
  { value: 'bts_chimie', label: 'BTS Chimie', category: 'superieur_court' },
  { value: 'bts_plastiques', label: 'BTS Plastiques et Composites', category: 'superieur_court' },
  { value: 'bts_sgm', label: 'BTS SGM', category: 'superieur_court', description: 'Science et Génie des Matériaux' },
  { value: 'bts_ccn', label: 'BTS CCN', category: 'superieur_court', description: 'Contrôle Commande Numérique' },
  { value: 'bts_cira', label: 'BTS CIRA', category: 'superieur_court', description: 'Contrôle Industriel et Régulation Automatique' },
  { value: 'bts_dut', label: 'BTS DUT', category: 'superieur_court', description: 'Domotique' },
  { value: 'bts_esthétique', label: 'BTS Esthétique-Cosmétique', category: 'superieur_court' },
  { value: 'bts_fashion', label: 'BTS Mode et Industries Textiles', category: 'superieur_court' },
  { value: 'bts_design', label: 'BTS Design Graphique', category: 'superieur_court' },
  { value: 'bts_archi', label: 'BTS Architecture', category: 'superieur_court' },
  { value: 'bts_espaces', label: 'BTS Design d\'Espace', category: 'superieur_court' },
  { value: 'bts_fashion_mode', label: 'BTS Design de Mode', category: 'superieur_court' },
  { value: 'bts_produit', label: 'BTS Design de Produits', category: 'superieur_court' },
  { value: 'bts_multimedia', label: 'BTS Multimédia', category: 'superieur_court' },
  { value: 'bts_audiovisuel', label: 'BTS Audiovisuel', category: 'superieur_court' },
  { value: 'bts_cinema', label: 'BTS Cinéma et Techniques Audiovisuelles', category: 'superieur_court' },
  { value: 'bts_photo', label: 'BTS Photographie', category: 'superieur_court' },
  { value: 'bts_son', label: 'BTS Techniques du Son', category: 'superieur_court' },
  { value: 'bts_sceno', label: 'BTS Scénographie', category: 'superieur_court' },
  { value: 'bts_agronomie', label: 'BTS Agronomie', category: 'superieur_court' },
  { value: 'bts_agri', label: 'BTS Productions Animales', category: 'superieur_court' },
  { value: 'bts_horticulture', label: 'BTS Horticulture', category: 'superieur_court' },
  { value: 'bts_paysage', label: 'BTS Aménagements Paysagers', category: 'superieur_court' },
  { value: 'bts_forestier', label: 'BTS Forêt', category: 'superieur_court' },
  { value: 'bts_viticole', label: 'BTS Viticulture-Œnologie', category: 'superieur_court' },
  { value: 'bts_aquaculture', label: 'BTS Aquaculture', category: 'superieur_court' },
  { value: 'bts_gestion_forestiere', label: 'BTS Gestion Forestière', category: 'superieur_court' },
  { value: 'bts_logistique', label: 'BTS Transport et Logistique', category: 'superieur_court' },
  { value: 'bts_assp', label: 'BTS ASSP', category: 'superieur_court', description: 'Accompagnement Soins et Services à la Personne' },
  { value: 'bts_esf', label: 'BTS ESF', category: 'superieur_court', description: 'Économie Sociale et Familiale' },
  { value: 'bts_sante', label: 'BTS SP3S', category: 'superieur_court', description: 'Santé, Parcours Sanitaires et Sociaux' },
  { value: 'bts_podologie', label: 'BTS Podo-Orthésiste', category: 'superieur_court' },
  { value: 'bts_opticien', label: 'BTS Opticien-Lunetier', category: 'superieur_court' },
  { value: 'bts_prothese', label: 'BTS Prothésiste Dentaire', category: 'superieur_court' },
  { value: 'bts_pharmaceutique', label: 'BTS Pharmacie', category: 'superieur_court' },
  { value: 'bts_social', label: 'BTS Économie Sociale et Familiale', category: 'superieur_court' },
  { value: 'bts_education', label: 'BTS Animation Sociale et Socioculturelle', category: 'superieur_court' },
  { value: 'bts_muc', label: 'BTS MUC', category: 'superieur_court', description: 'Management des Unités Commerciales' },
  { value: 'bts_commerce_international', label: 'BTS Commerce International', category: 'superieur_court' },
  { value: 'bts_marketing', label: 'BTS Communication', category: 'superieur_court' },
  { value: 'bts_pub', label: 'BTS Communication et Médiation', category: 'superieur_court' },
  { value: 'bts_journalisme', label: 'BTS Journalisme', category: 'superieur_court' },
  { value: 'bts_nrc', label: 'Bts nrc', category: 'superieur_court', description: 'Négociation relation client' },
  { value: 'bts_ag', label: 'BTS Assistant de Gestion', category: 'superieur_court' },
  { value: 'bts_gpm', label: 'BTS Gestion de Production', category: 'superieur_court' },
  { value: 'bts_qse', label: 'BTS QSE', category: 'superieur_court', description: 'Qualité Sécurité Environnement' },
  { value: 'bts_imprimerie', label: 'BTS Imprimerie', category: 'superieur_court' },
  { value: 'bts_édition', label: 'BTS Édition', category: 'superieur_court' },
  { value: 'bts_métiers_art', label: 'BTS Métiers d\'Art', category: 'superieur_court' },
  { value: 'bts_maroquinerie', label: 'BTS Maroquinerie', category: 'superieur_court' },
  { value: 'bts_bijouterie', label: 'BTS Bijouterie-Joaillerie', category: 'superieur_court' },
  { value: 'bts_céramique', label: 'BTS Céramique', category: 'superieur_court' },
  { value: 'bts_verrerie', label: 'BTS Verrerie', category: 'superieur_court' },
  { value: 'bts_musique', label: 'BTS Musiques Actuelles', category: 'superieur_court' },
  { value: 'bts_danse', label: 'BTS Danse', category: 'superieur_court' },
  { value: 'bts_théâtre', label: 'Bts théâtre', category: 'superieur_court' },
  { value: 'bts_médiation', label: 'BTS Médiation Culturelle', category: 'superieur_court' },
  { value: 'bts_patrimoine', label: 'BTS Métiers du Patrimoine', category: 'superieur_court' },
  { value: 'bts_nautisme', label: 'BTS Nautisme', category: 'superieur_court' },
  { value: 'bts_aéronautique', label: 'BTS Aéronautique', category: 'superieur_court' },
  { value: 'bts_aéro', label: 'BTS Systèmes Aéronautiques', category: 'superieur_court' },
  { value: 'bts_navale', label: 'BTS Construction Navale', category: 'superieur_court' },
  { value: 'bts_agroalimentaire', label: 'BTS Bioanalyses et Contrôles', category: 'superieur_court' },
  { value: 'bts_agro_industrie', label: 'BTS Agroalimentaire', category: 'superieur_court' },
  { value: 'bts_dietetique', label: 'BTS Diététique', category: 'superieur_court' },
  { value: 'bts_restauration', label: 'BTS Arts Culinaires', category: 'superieur_court' },
  { value: 'bts_banque', label: 'BTS Banque', category: 'superieur_court' },
  { value: 'bts_assurance', label: 'Bts assurance', category: 'superieur_court' },
  { value: 'bts_immobilier', label: 'BTS Professions Immobilières', category: 'superieur_court' },
  { value: 'bts_comptabilite', label: 'BTS Comptabilité', category: 'superieur_court' },
  { value: 'bts_gestion', label: 'Bts gestion', category: 'superieur_court' },
  { value: 'bts_dsi', label: 'BTS DSI', category: 'superieur_court', description: 'Développement de Solutions Informatiques' },
  { value: 'bts_cybersecurite', label: 'BTS Cybersécurité', category: 'superieur_court' },
  { value: 'bts_reseaux', label: 'BTS Systèmes et Réseaux', category: 'superieur_court' },
  { value: 'bts_cloud', label: 'BTS Cloud Computing', category: 'superieur_court' },
  { value: 'bts_data', label: 'BTS Data', category: 'superieur_court', description: 'Science des Données' },
  { value: 'bts_ia', label: 'BTS Intelligence Artificielle', category: 'superieur_court' },
  { value: 'bts_robotique', label: 'BTS Robotique', category: 'superieur_court' },
  { value: 'bts_drones', label: 'BTS Drones', category: 'superieur_court' },

  // BUT - BACHELOR UNIVERSITAIRE DE TECHNOLOGIE
  { value: 'but_info', label: 'BUT Informatique', category: 'superieur_court' },
  { value: 'but_rt', label: 'BUT R&T', category: 'superieur_court', description: 'Réseaux et Télécommunications' },
  { value: 'but_geii', label: 'BUT GEII', category: 'superieur_court', description: 'Génie Électrique et Informatique Industrielle' },
  { value: 'but_gmp', label: 'BUT GMP', category: 'superieur_court', description: 'Génie Mécanique et Productique' },
  { value: 'but_gcgp', label: 'BUT GCGP', category: 'superieur_court', description: 'Génie Civil et Construction Durable' },
  { value: 'but_tc', label: 'BUT TC', category: 'superieur_court', description: 'Techniques de Commercialisation' },
  { value: 'but_gaco', label: 'BUT GACO', category: 'superieur_court', description: 'Gestion Administrative et Commerciale' },
  { value: 'but_hse', label: 'BUT Hygiène Sécurité Environnement', category: 'superieur_court' },
  { value: 'but_qlio', label: 'BUT QLIO', category: 'superieur_court', description: 'Qualité Logistique Industrielle et Organisation' },
  { value: 'but_stid', label: 'BUT STID', category: 'superieur_court', description: 'Statistique et Informatique Décisionnelle' },
  { value: 'but_bio', label: 'BUT Biologie', category: 'superieur_court' },
  { value: 'but_chimie', label: 'BUT Chimie', category: 'superieur_court' },
  { value: 'but_génie_biologique', label: 'BUT Génie Biologique', category: 'superieur_court' },
  { value: 'but_science_co', label: 'BUT Sciences et Génie des Matériaux', category: 'superieur_court' },
  { value: 'but_info_com', label: 'BUT Information-Communication', category: 'superieur_court' },
  { value: 'but_mmi', label: 'BUT MMI', category: 'superieur_court', description: 'Métiers du Multimédia et de l\'Internet' },
  { value: 'but_cj', label: 'BUT Carrières Juridiques', category: 'superieur_court' },
  { value: 'but_cs', label: 'BUT Carrières Sociales', category: 'superieur_court' },
  { value: 'but_gestion', label: 'BUT Gestion des Entreprises', category: 'superieur_court' },
  { value: 'but_logistique', label: 'BUT Logistique', category: 'superieur_court' },
  { value: 'but_tourisme', label: 'BUT Tourisme', category: 'superieur_court' },
  { value: 'but_hôtellerie', label: 'BUT Hôtellerie-Restauration', category: 'superieur_court' },
  { value: 'but_agronomie', label: 'BUT Agronomie', category: 'superieur_court' },
  { value: 'but_agro', label: 'BUT Agroécologie', category: 'superieur_court' },
  { value: 'but_aménagement', label: 'BUT Aménagement', category: 'superieur_court' },
  { value: 'but_environnement', label: 'BUT Environnement', category: 'superieur_court' },
  { value: 'but_santé', label: 'BUT Santé', category: 'superieur_court' },
  { value: 'but_social', label: 'BUT Animation Sociale', category: 'superieur_court' },

  // LICENCES
  { value: 'licence_droit', label: 'Licence Droit', category: 'superieur_long' },
  { value: 'licence_economie', label: 'Licence Économie', category: 'superieur_long' },
  { value: 'licence_gestion', label: 'Licence Gestion', category: 'superieur_long' },
  { value: 'licence_ae', label: 'Licence Administration Économique et Sociale', category: 'superieur_long' },
  { value: 'licence_math', label: 'Licence Mathématiques', category: 'superieur_long' },
  { value: 'licence_info', label: 'Licence Informatique', category: 'superieur_long' },
  { value: 'licence_physique', label: 'Licence Physique', category: 'superieur_long' },
  { value: 'licence_chimie', label: 'Licence Chimie', category: 'superieur_long' },
  { value: 'licence_bio', label: 'Licence Biologie', category: 'superieur_long' },
  { value: 'licence_svt', label: 'Licence SVT', category: 'superieur_long', description: 'Sciences de la Vie et de la Terre' },
  { value: 'licence_histoire', label: 'Licence Histoire', category: 'superieur_long' },
  { value: 'licence_geographie', label: 'Licence Géographie', category: 'superieur_long' },
  { value: 'licence_histoire_art', label: 'Licence Histoire de l\'Art', category: 'superieur_long' },
  { value: 'licence_archéologie', label: 'Licence Archéologie', category: 'superieur_long' },
  { value: 'licence_philosophie', label: 'Licence Philosophie', category: 'superieur_long' },
  { value: 'licence_lettres', label: 'Licence Lettres', category: 'superieur_long' },
  { value: 'licence_langues', label: 'Licence Langues Étrangères', category: 'superieur_long' },
  { value: 'licence_anglais', label: 'Licence LLCER Anglais', category: 'superieur_long' },
  { value: 'licence_allemand', label: 'Licence LLCER Allemand', category: 'superieur_long' },
  { value: 'licence_espagnol', label: 'Licence LLCER Espagnol', category: 'superieur_long' },
  { value: 'licence_italien', label: 'Licence LLCER Italien', category: 'superieur_long' },
  { value: 'licence_chinois', label: 'Licence LLCER Chinois', category: 'superieur_long' },
  { value: 'licence_japonais', label: 'Licence LLCER Japonais', category: 'superieur_long' },
  { value: 'licence_arabe', label: 'Licence LLCER Arabe', category: 'superieur_long' },
  { value: 'licence_russe', label: 'Licence LLCER Russe', category: 'superieur_long' },
  { value: 'licence_portugais', label: 'Licence LLCER Portugais', category: 'superieur_long' },
  { value: 'licence_lea', label: 'Licence LEA', category: 'superieur_long', description: 'Langues Étrangères Appliquées' },
  { value: 'licence_psychologie', label: 'Licence Psychologie', category: 'superieur_long' },
  { value: 'licence_sociologie', label: 'Licence Sociologie', category: 'superieur_long' },
  { value: 'licence_anthropologie', label: 'Licence Anthropologie', category: 'superieur_long' },
  { value: 'licence_science_politique', label: 'Licence Science Politique', category: 'superieur_long' },
  { value: 'licence_info_com', label: 'Licence Information-Communication', category: 'superieur_long' },
  { value: 'licence_médiation', label: 'Licence Médiation Culturelle', category: 'superieur_long' },
  { value: 'licence_education', label: 'Licence Sciences de l\'Éducation', category: 'superieur_long' },
  { value: 'licence_staps', label: 'Licence STAPS', category: 'superieur_long', description: 'Sciences et Techniques des Activités Physiques et Sportives' },
  { value: 'licence_musique', label: 'Licence Musicologie', category: 'superieur_long' },
  { value: 'licence_arts', label: 'Licence Arts', category: 'superieur_long' },
  { value: 'licence_design', label: 'Licence Design', category: 'superieur_long' },
  { value: 'licence_cinema', label: 'Licence Cinéma', category: 'superieur_long' },
  { value: 'licence_theatre', label: 'Licence Théâtre', category: 'superieur_long' },
  { value: 'licence_danse', label: 'Licence Danse', category: 'superieur_long' },
  { value: 'licence_mode', label: 'Licence Mode', category: 'superieur_long' },
  { value: 'licence_archi', label: 'Licence Architecture', category: 'superieur_long' },
  { value: 'licence_paysage', label: 'Licence Paysage', category: 'superieur_long' },
  { value: 'licence_urbanisme', label: 'Licence Urbanisme', category: 'superieur_long' },
  { value: 'licence_patrimoine', label: 'Licence Patrimoine', category: 'superieur_long' },
  { value: 'licence_medecine', label: 'Licence Médecine', category: 'superieur_long' },
  { value: 'licence_pharmacie', label: 'Licence Pharmacie', category: 'superieur_long' },
  { value: 'licence_odontologie', label: 'Licence Odontologie', category: 'superieur_long' },
  { value: 'licence_sage_femme', label: 'Licence Maïeutique', category: 'superieur_long' },
  { value: 'licence_kinesitherapie', label: 'Licence Kinésithérapie', category: 'superieur_long' },
  { value: 'licence_infirmier', label: 'Licence Soins Infirmiers', category: 'superieur_long' },
  { value: 'licence_pedicure', label: 'Licence Pédicure-Podologue', category: 'superieur_long' },
  { value: 'licence_orthophonie', label: 'Licence Orthophonie', category: 'superieur_long' },
  { value: 'licence_orthoptie', label: 'Licence Orthoptie', category: 'superieur_long' },
  { value: 'licence_ergotherapie', label: 'Licence Ergothérapie', category: 'superieur_long' },
  { value: 'licence_dietetique', label: 'Licence Diététique', category: 'superieur_long' },
  { value: 'licence_ims', label: 'Licence Ingénierie Mathématique', category: 'superieur_long' },
  { value: 'licence_double_diplome', label: 'Licence Double Diplôme', category: 'superieur_long' },
  { value: 'licence_pro_droit', label: 'Licence Pro Droit', category: 'superieur_long' },
  { value: 'licence_pro_commerce', label: 'Licence Pro Commerce', category: 'superieur_long' },
  { value: 'licence_pro_info', label: 'Licence Pro Informatique', category: 'superieur_long' },
  { value: 'licence_pro_industrie', label: 'Licence Pro Industrie', category: 'superieur_long' },
  { value: 'licence_pro_environnement', label: 'Licence Pro Environnement', category: 'superieur_long' },
  { value: 'licence_pro_tourisme', label: 'Licence Pro Tourisme', category: 'superieur_long' },

  // MASTERS
  { value: 'master_droit_public', label: 'Master Droit Public', category: 'superieur_long' },
  { value: 'master_droit_prive', label: 'Master Droit Privé', category: 'superieur_long' },
  { value: 'master_droit_affaires', label: 'Master Droit des Affaires', category: 'superieur_long' },
  { value: 'master_droit_social', label: 'Master Droit Social', category: 'superieur_long' },
  { value: 'master_droit_fiscal', label: 'Master Droit Fiscal', category: 'superieur_long' },
  { value: 'master_droit_penal', label: 'Master Droit Pénal', category: 'superieur_long' },
  { value: 'master_droit_international', label: 'Master Droit International', category: 'superieur_long' },
  { value: 'master_droit_europeen', label: 'Master Droit Européen', category: 'superieur_long' },
  { value: 'master_droit_immobilier', label: 'Master Droit Immobilier', category: 'superieur_long' },
  { value: 'master_droit_numerique', label: 'Master Droit du Numérique', category: 'superieur_long' },
  { value: 'master_droit_sante', label: 'Master Droit de la Santé', category: 'superieur_long' },
  { value: 'master_droit_environnement', label: 'Master Droit de l\'Environnement', category: 'superieur_long' },
  { value: 'master_economie', label: 'Master Économie', category: 'superieur_long' },
  { value: 'master_econometrie', label: 'Master Économétrie', category: 'superieur_long' },
  { value: 'master_finance', label: 'Master Finance', category: 'superieur_long' },
  { value: 'master_banque', label: 'Master Banque', category: 'superieur_long' },
  { value: 'master_assurance', label: 'Master Actuariat/Assurance', category: 'superieur_long' },
  { value: 'master_marketing', label: 'Master Marketing', category: 'superieur_long' },
  { value: 'master_commerce', label: 'Master Commerce International', category: 'superieur_long' },
  { value: 'master_rh', label: 'Master Ressources Humaines', category: 'superieur_long' },
  { value: 'master_grh', label: 'Master Gestion des Ressources Humaines', category: 'superieur_long' },
  { value: 'master_audit', label: 'Master Audit-Contrôle', category: 'superieur_long' },
  { value: 'master_compta', label: 'Master Comptabilité', category: 'superieur_long' },
  { value: 'master_gestion', label: 'Master Management', category: 'superieur_long' },
  { value: 'master_strategie', label: 'Master Stratégie', category: 'superieur_long' },
  { value: 'master_innovation', label: 'Master Innovation-Entrepreneuriat', category: 'superieur_long' },
  { value: 'master_data', label: 'Master Data Science', category: 'superieur_long' },
  { value: 'master_ia', label: 'Master Intelligence Artificielle', category: 'superieur_long' },
  { value: 'master_cybersecurite', label: 'Master Cybersécurité', category: 'superieur_long' },
  { value: 'master_informatique', label: 'Master Informatique', category: 'superieur_long' },
  { value: 'master_telecom', label: 'Master Télécommunications', category: 'superieur_long' },
  { value: 'master_reseaux', label: 'Master Réseaux', category: 'superieur_long' },
  { value: 'master_cloud', label: 'Master Cloud Computing', category: 'superieur_long' },
  { value: 'master_blockchain', label: 'Master Blockchain', category: 'superieur_long' },
  { value: 'master_data_analytics', label: 'Master Data Analytics', category: 'superieur_long' },
  { value: 'master_math_appliquees', label: 'Master Mathématiques Appliquées', category: 'superieur_long' },
  { value: 'master_physique', label: 'Master Physique', category: 'superieur_long' },
  { value: 'master_chimie', label: 'Master Chimie', category: 'superieur_long' },
  { value: 'master_bio', label: 'Master Biologie', category: 'superieur_long' },
  { value: 'master_biotech', label: 'Master Biotechnologies', category: 'superieur_long' },
  { value: 'master_biodiversite', label: 'Master Biodiversité', category: 'superieur_long' },
  { value: 'master_ecologie', label: 'Master Écologie', category: 'superieur_long' },
  { value: 'master_environnement', label: 'Master Environnement', category: 'superieur_long' },
  { value: 'master_geologie', label: 'Master Géologie', category: 'superieur_long' },
  { value: 'master_geophysique', label: 'Master Géophysique', category: 'superieur_long' },
  { value: 'master_oceanographie', label: 'Master Océanographie', category: 'superieur_long' },
  { value: 'master_meteo', label: 'Master Météorologie', category: 'superieur_long' },
  { value: 'master_astronomie', label: 'Master Astronomie', category: 'superieur_long' },
  { value: 'master_histoire', label: 'Master Histoire', category: 'superieur_long' },
  { value: 'master_geographie', label: 'Master Géographie', category: 'superieur_long' },
  { value: 'master_histoire_art', label: 'Master Histoire de l\'Art', category: 'superieur_long' },
  { value: 'master_archeologie', label: 'Master Archéologie', category: 'superieur_long' },
  { value: 'master_philosophie', label: 'Master Philosophie', category: 'superieur_long' },
  { value: 'master_lettres', label: 'Master Lettres', category: 'superieur_long' },
  { value: 'master_llcer', label: 'Master LLCER', category: 'superieur_long', description: 'Langues, Littératures et Civilisations Étrangères' },
  { value: 'master_lea', label: 'Master LEA', category: 'superieur_long', description: 'Langues Étrangères Appliquées' },
  { value: 'master_traduction', label: 'Master Traduction', category: 'superieur_long' },
  { value: 'master_interpretation', label: 'Master Interprétation', category: 'superieur_long' },
  { value: 'master_fle', label: 'Master FLE', category: 'superieur_long', description: 'Français Langue Étrangère' },
  { value: 'master_fls', label: 'Master FLS', category: 'superieur_long', description: 'Français Langue Seconde' },
  { value: 'master_journalisme', label: 'Master Journalisme', category: 'superieur_long' },
  { value: 'master_communication', label: 'Master Communication', category: 'superieur_long' },
  { value: 'master_pub', label: 'Master Publicité', category: 'superieur_long' },
  { value: 'master_rp', label: 'Master Relations Publiques', category: 'superieur_long' },
  { value: 'master_medias', label: 'Master Médias Numériques', category: 'superieur_long' },
  { value: 'master_cinema', label: 'Master Cinéma', category: 'superieur_long' },
  { value: 'master_audiovisuel', label: 'Master Audiovisuel', category: 'superieur_long' },
  { value: 'master_radio', label: 'Master Radio', category: 'superieur_long' },
  { value: 'master_tv', label: 'Master Télévision', category: 'superieur_long' },
  { value: 'master_documentaire', label: 'Master Documentaire', category: 'superieur_long' },
  { value: 'master_photo', label: 'Master Photographie', category: 'superieur_long' },
  { value: 'master_design_graphique', label: 'Master Design Graphique', category: 'superieur_long' },
  { value: 'master_design_produit', label: 'Master Design Produit', category: 'superieur_long' },
  { value: 'master_fashion', label: 'Master Mode', category: 'superieur_long' },
  { value: 'master_archi', label: 'Master Architecture', category: 'superieur_long' },
  { value: 'master_urbanisme', label: 'Master Urbanisme', category: 'superieur_long' },
  { value: 'master_paysage', label: 'Master Paysage', category: 'superieur_long' },
  { value: 'master_patrimoine', label: 'Master Patrimoine', category: 'superieur_long' },
  { value: 'master_museologie', label: 'Master Muséologie', category: 'superieur_long' },
  { value: 'master_psychologie', label: 'Master Psychologie', category: 'superieur_long' },
  { value: 'master_psychologie_clinique', label: 'Master Psychologie Clinique', category: 'superieur_long' },
  { value: 'master_neuropsychologie', label: 'Master Neuropsychologie', category: 'superieur_long' },
  { value: 'master_psychologie_travail', label: 'Master Psychologie du Travail', category: 'superieur_long' },
  { value: 'master_sociologie', label: 'Master Sociologie', category: 'superieur_long' },
  { value: 'master_anthropologie', label: 'Master Anthropologie', category: 'superieur_long' },
  { value: 'master_ethnologie', label: 'Master Ethnologie', category: 'superieur_long' },
  { value: 'master_science_pol', label: 'Master Science Politique', category: 'superieur_long' },
  { value: 'master_administration', label: 'Master Administration Publique', category: 'superieur_long' },
  { value: 'master_affaires_publiques', label: 'Master Affaires Publiques', category: 'superieur_long' },
  { value: 'master_politiques_publiques', label: 'Master Politiques Publiques', category: 'superieur_long' },
  { value: 'master_relations_internationales', label: 'Master Relations Internationales', category: 'superieur_long' },
  { value: 'master_securite', label: 'Master Sécurité Internationale', category: 'superieur_long' },
  { value: 'master_defense', label: 'Master Défense', category: 'superieur_long' },
  { value: 'master_education', label: 'Master Sciences de l\'Éducation', category: 'superieur_long' },
  { value: 'master_enseignement', label: 'Master Métiers de l\'Enseignement', category: 'superieur_long' },
  { value: 'master_ingénierie_pedagogique', label: 'Master Ingénierie Pédagogique', category: 'superieur_long' },
  { value: 'master_staps', label: 'Master STAPS', category: 'superieur_long', description: 'Sciences et Techniques des Activités Physiques et Sportives' },
  { value: 'master_entrainement', label: 'Master Entraînement Sportif', category: 'superieur_long' },
  { value: 'master_management_sport', label: 'Master Management du Sport', category: 'superieur_long' },
  { value: 'master_medecine', label: 'Master Médecine (DES)', category: 'superieur_long', description: 'Diplôme d\'Études Spécialisées' },
  { value: 'master_chirurgie', label: 'Master Chirurgie (DESC)', category: 'superieur_long', description: 'Diplôme d\'Études Spécialisées Complémentaires' },
  { value: 'master_specialite_med', label: 'Master Spécialité Médicale', category: 'superieur_long' },
  { value: 'master_sante_publique', label: 'Master Santé Publique', category: 'superieur_long' },
  { value: 'master_epidemiologie', label: 'Master Épidémiologie', category: 'superieur_long' },
  { value: 'master_biostatistiques', label: 'Master Biostatistiques', category: 'superieur_long' },
  { value: 'master_ingenierie_sante', label: 'Master Ingénierie de la Santé', category: 'superieur_long' },
  { value: 'master_sante_mentale', label: 'Master Santé Mentale', category: 'superieur_long' },
  { value: 'master_addictologie', label: 'Master Addictologie', category: 'superieur_long' },
  { value: 'master_gerontologie', label: 'Master Gérontologie', category: 'superieur_long' },
  { value: 'master_pediatrie', label: 'Master Pédiatrie', category: 'superieur_long' },
  { value: 'master_oncologie', label: 'Master Oncologie', category: 'superieur_long' },
  { value: 'master_cardiologie', label: 'Master Cardiologie', category: 'superieur_long' },
  { value: 'master_neurologie', label: 'Master Neurologie', category: 'superieur_long' },
  { value: 'master_psychiatrie', label: 'Master Psychiatrie', category: 'superieur_long' },
  { value: 'master_dermatologie', label: 'Master Dermatologie', category: 'superieur_long' },
  { value: 'master_orl', label: 'Master ORL', category: 'superieur_long' },
  { value: 'master_ophtalmologie', label: 'Master Ophtalmologie', category: 'superieur_long' },
  { value: 'master_gynecologie', label: 'Master Gynécologie-Obstétrique', category: 'superieur_long' },
  { value: 'master_anesthesie', label: 'Master Anesthésie-Réanimation', category: 'superieur_long' },
  { value: 'master_urgences', label: 'Master Médecine d\'Urgence', category: 'superieur_long' },
  { value: 'master_imagerie', label: 'Master Imagerie Médicale', category: 'superieur_long' },
  { value: 'master_biologie_medicale', label: 'Master Biologie Médicale', category: 'superieur_long' },
  { value: 'master_genetique', label: 'Master Génétique', category: 'superieur_long' },
  { value: 'master_immunologie', label: 'Master Immunologie', category: 'superieur_long' },
  { value: 'master_microbiologie', label: 'Master Microbiologie', category: 'superieur_long' },
  { value: 'master_recherche_clinique', label: 'Master Recherche Clinique', category: 'superieur_long' },
  { value: 'master_pharmacie', label: 'Master Pharmacie', category: 'superieur_long' },
  { value: 'master_pharmacologie', label: 'Master Pharmacologie', category: 'superieur_long' },
  { value: 'master_galenique', label: 'Master Galénique', category: 'superieur_long' },
  { value: 'master_toxicologie', label: 'Master Toxicologie', category: 'superieur_long' },
  { value: 'master_odontologie', label: 'Master Odontologie', category: 'superieur_long' },
  { value: 'master_chirurgie_dentaire', label: 'Master Chirurgie Dentaire', category: 'superieur_long' },
  { value: 'master_orthodontie', label: 'Master Orthodontie', category: 'superieur_long' },
  { value: 'master_endodontie', label: 'Master Endodontie', category: 'superieur_long' },
  { value: 'master_paro', label: 'Master Parodontologie', category: 'superieur_long' },
  { value: 'master_prothese_dentaire', label: 'Master Prothèse Dentaire', category: 'superieur_long' },
  { value: 'master_veterinaire', label: 'Master Vétérinaire', category: 'superieur_long' },
  { value: 'master_sciences_infirmieres', label: 'Master Sciences Infirmières', category: 'superieur_long' },
  { value: 'master_ingenierie', label: 'Master Ingénierie', category: 'superieur_long' },
  { value: 'master_genie_civil', label: 'Master Génie Civil', category: 'superieur_long' },
  { value: 'master_genie_mecanique', label: 'Master Génie Mécanique', category: 'superieur_long' },
  { value: 'master_genie_electrique', label: 'Master Génie Électrique', category: 'superieur_long' },
  { value: 'master_genie_chimique', label: 'Master Génie Chimique', category: 'superieur_long' },
  { value: 'master_genie_industriel', label: 'Master Génie Industriel', category: 'superieur_long' },
  { value: 'master_aeronautique', label: 'Master Aéronautique', category: 'superieur_long' },
  { value: 'master_spatial', label: 'Master Spatial', category: 'superieur_long' },
  { value: 'master_automobile', label: 'Master Automobile', category: 'superieur_long' },
  { value: 'master_ferroviaire', label: 'Master Ferroviaire', category: 'superieur_long' },
  { value: 'master_naval', label: 'Master Naval', category: 'superieur_long' },
  { value: 'master_energie', label: 'Master Énergie', category: 'superieur_long' },
  { value: 'master_nucleaire', label: 'Master Nucléaire', category: 'superieur_long' },
  { value: 'master_eolien', label: 'Master Énergies Renouvelables', category: 'superieur_long' },
  { value: 'master_materiaux', label: 'Master Matériaux', category: 'superieur_long' },
  { value: 'master_nanotechnologies', label: 'Master Nanotechnologies', category: 'superieur_long' },
  { value: 'master_robotique', label: 'Master Robotique', category: 'superieur_long' },
  { value: 'master_mecatronique', label: 'Master Mécatronique', category: 'superieur_long' },
  { value: 'master_electronique', label: 'Master Électronique', category: 'superieur_long' },
  { value: 'master_optoelectronique', label: 'Master Optoélectronique', category: 'superieur_long' },
  { value: 'master_telecommunications', label: 'Master Télécommunications', category: 'superieur_long' },
  { value: 'master_systemes_embarques', label: 'Master Systèmes Embarqués', category: 'superieur_long' },
  { value: 'master_iot', label: 'Master Internet des Objets', category: 'superieur_long' },
  { value: 'master_agronomie', label: 'Master Agronomie', category: 'superieur_long' },
  { value: 'master_agroalimentaire', label: 'Master Agroalimentaire', category: 'superieur_long' },
  { value: 'master_agroecologie', label: 'Master Agroécologie', category: 'superieur_long' },
  { value: 'master_sciences_aliments', label: 'Master Sciences des Aliments', category: 'superieur_long' },
  { value: 'master_viticulture', label: 'Master Viticulture-Œnologie', category: 'superieur_long' },
  { value: 'master_foret', label: 'Master Forêt', category: 'superieur_long' },
  { value: 'master_horticulture', label: 'Master Horticulture', category: 'superieur_long' },
  { value: 'master_zootechnie', label: 'Master Zootechnie', category: 'superieur_long' },
  { value: 'master_aquaculture', label: 'Master Aquaculture', category: 'superieur_long' },
  { value: 'master_pêche', label: 'Master Pêche', category: 'superieur_long' },
  { value: 'master_tourisme', label: 'Master Tourisme', category: 'superieur_long' },
  { value: 'master_hotellerie', label: 'Master Hôtellerie', category: 'superieur_long' },
  { value: 'master_evenementiel', label: 'Master Événementiel', category: 'superieur_long' },
  { value: 'master_loisirs', label: 'Master Loisirs', category: 'superieur_long' },
  { value: 'master_territoires', label: 'Master Aménagement des Territoires', category: 'superieur_long' },
  { value: 'master_developpement_durable', label: 'Master Développement Durable', category: 'superieur_long' },
  { value: 'master_climat', label: 'Master Sciences du Climat', category: 'superieur_long' },
  { value: 'master_eau', label: 'Master Sciences de l\'Eau', category: 'superieur_long' },
  { value: 'master_dechets', label: 'Master Gestion des Déchets', category: 'superieur_long' },

  // ÉCOLES DE COMMERCE
  { value: 'esc_bachelor', label: 'Bachelor École de Commerce', category: 'superieur_long' },
  { value: 'esc_pge', label: 'Programme Grande École', category: 'superieur_long' },
  { value: 'esc_msc', label: 'MSc École de Commerce', category: 'superieur_long' },
  { value: 'esc_ms', label: 'Mastère Spécialisé', category: 'superieur_long' },
  { value: 'esc_mba', label: 'MBA', category: 'superieur_long', description: 'Master of Business Administration' },
  { value: 'esc_executive', label: 'Executive Education', category: 'superieur_long' },

  // ÉCOLES D'INGÉNIEURS
  { value: 'ei_prepa', label: 'Prépa intégrée Ingénieur', category: 'superieur_long' },
  { value: 'ei_pge', label: 'Diplôme d\'Ingénieur', category: 'superieur_long' },
  { value: 'ei_specialite', label: 'Ingénieur Spécialisé', category: 'superieur_long' },
  { value: 'ei_architecte', label: 'Diplôme d\'Architecte', category: 'superieur_long' },
  { value: 'ei_ingenieur_recherche', label: 'Ingénieur de Recherche', category: 'superieur_long' },

  // CLASSES PRÉPARATOIRES
  { value: 'cpge_mpsi', label: 'CPGE MPSI', category: 'superieur_long', description: 'Mathématiques, Physique, Sciences de l\'Ingénieur' },
  { value: 'cpge_mp', label: 'CPGE MP', category: 'superieur_long', description: 'Mathématiques, Physique' },
  { value: 'cpge_pc', label: 'CPGE PC', category: 'superieur_long', description: 'Physique, Chimie' },
  { value: 'cpge_psi', label: 'CPGE PSI', category: 'superieur_long', description: 'Physique, Sciences de l\'Ingénieur' },
  { value: 'cpge_pt', label: 'CPGE PT', category: 'superieur_long', description: 'Physique, Technologie' },
  { value: 'cpge_bcpst', label: 'CPGE BCPST', category: 'superieur_long', description: 'Biologie, Chimie, Physique, Sciences de la Terre' },
  { value: 'cpge_ecs', label: 'CPGE ECS', category: 'superieur_long', description: 'Économique et Commerciale Scientifique' },
  { value: 'cpge_ec', label: 'CPGE ECE', category: 'superieur_long', description: 'Économique et Commerciale Économique' },
  { value: 'cpge_ens_cachan', label: 'CPGE ENS Cachan', category: 'superieur_long' },
  { value: 'cpge_ens_ulm', label: 'CPGE ENS Ulm', category: 'superieur_long' },
  { value: 'cpge_lyon', label: 'CPGE ENS Lyon', category: 'superieur_long' },
  { value: 'cpge_lettres', label: 'CPGE Lettres', category: 'superieur_long' },
  { value: 'cpge_khagne', label: 'CPGE Khâgne', category: 'superieur_long', description: 'Lettres Supérieures' },
  { value: 'cpge_hypokhagne', label: 'CPGE Hypokhâgne', category: 'superieur_long', description: 'Lettres Supérieures 1ère année' },
  { value: 'cpge_bl', label: 'CPGE BL', category: 'superieur_long', description: 'B/L Lettres et Sciences Sociales' },
  { value: 'cpge_agro', label: 'CPSE Agro-Véto', category: 'superieur_long' },
  { value: 'cpge_manaa', label: 'MANAA', category: 'superieur_long', description: 'Mise à Niveau en Arts Appliqués' },

  // FORMATIONS EN APPRENTISSAGE
  { value: 'app_cap', label: 'CAP en Apprentissage', category: 'apprentissage' },
  { value: 'app_bac_pro', label: 'Bac Pro en Apprentissage', category: 'apprentissage' },
  { value: 'app_bts', label: 'BTS en Apprentissage', category: 'apprentissage' },
  { value: 'app_but', label: 'BUT en Apprentissage', category: 'apprentissage' },
  { value: 'app_licence', label: 'Licence en Apprentissage', category: 'apprentissage' },
  { value: 'app_master', label: 'Master en Apprentissage', category: 'apprentissage' },
  { value: 'app_diplome_ingenieur', label: 'Diplôme d\'Ingénieur en Apprentissage', category: 'apprentissage' },
  { value: 'app_diplome_commerce', label: 'Diplôme École de Commerce en Apprentissage', category: 'apprentissage' },
  { value: 'app_bp', label: 'Brevet Professionnel en Apprentissage', category: 'apprentissage' },
  { value: 'app_bma', label: 'Brevet des Métiers d\'Art en Apprentissage', category: 'apprentissage' },
  { value: 'app_cs', label: 'Certificat de Spécialisation', category: 'apprentissage' },
  { value: 'app_fcil', label: 'FCIL', category: 'apprentissage', description: 'Formation Complémentaire d\'Initiative Locale' },
  { value: 'app_tp', label: 'Titre Professionnel', category: 'apprentissage' },
  { value: 'app_rncp', label: 'Certification RNCP', category: 'apprentissage' },

  // FORMATION CONTINUE
  { value: 'fc_cap', label: 'CAP en Formation Continue', category: 'formation_continue' },
  { value: 'fc_bep', label: 'BEP en Formation Continue', category: 'formation_continue' },
  { value: 'fc_bac_pro', label: 'Bac Pro en Formation Continue', category: 'formation_continue' },
  { value: 'fc_bts', label: 'BTS en Formation Continue', category: 'formation_continue' },
  { value: 'fc_licence', label: 'Licence en Formation Continue', category: 'formation_continue' },
  { value: 'fc_master', label: 'Master en Formation Continue', category: 'formation_continue' },
  { value: 'fc_vae', label: 'VAE', category: 'formation_continue', description: 'Validation des Acquis de l\'Expérience' },
  { value: 'fc_dif', label: 'CPF', category: 'formation_continue', description: 'Compte Personnel de Formation' },
  { value: 'fc_cpf_congé', label: 'CPF de Transition', category: 'formation_continue' },
  { value: 'fc_projet_transition', label: 'Projet de Transition Professionnelle', category: 'formation_continue' },
  { value: 'fc_bilan_competences', label: 'Bilan de Compétences', category: 'formation_continue' },
  { value: 'fc_vap', label: 'VAP', category: 'formation_continue', description: 'Validation des Acquis Professionnels' },
  { value: 'fc_daeu', label: 'DAEU', category: 'formation_continue', description: 'Diplôme d\'Accès aux Études Universitaires' },
  { value: 'fc_cned', label: 'CNED', category: 'formation_continue', description: 'Centre National d\'Enseignement à Distance' },
  { value: 'fc_cnam', label: 'CNAM', category: 'formation_continue', description: 'Conservatoire National des Arts et Métiers' },
  { value: 'fc_afpa', label: 'AFPA', category: 'formation_continue' },
  { value: 'fc_greta', label: 'GRETA', category: 'formation_continue' },
  { value: 'fc_mooc', label: 'MOOC', category: 'formation_continue' },
  { value: 'fc_spooc', label: 'SPOOC', category: 'formation_continue' },
  { value: 'fc_certification_pro', label: 'Certification Professionnelle', category: 'formation_continue' },
  { value: 'fc_cqp', label: 'CQP', category: 'formation_continue', description: 'Certificat de Qualification Professionnelle' },

  // FORMATIONS INTERNATIONALES
  { value: 'intl_bac_ibo', label: 'Baccalauréat International (IB)', category: 'superieur_long' },
  { value: 'intl_abibac', label: 'AbiBac', category: 'superieur_long', description: 'Baccalauréat Franco-Allemand' },
  { value: 'intl_esabac', label: 'Esabac', category: 'superieur_long', description: 'Baccalauréat Franco-Italien' },
  { value: 'intl_bachibac', label: 'Bachibac', category: 'superieur_long', description: 'Baccalauréat Franco-Espagnol' },
  { value: 'intl_erasmus', label: 'Erasmus+', category: 'superieur_long' },
  { value: 'intl_double_diplome', label: 'Double Diplôme International', category: 'superieur_long' },

  // DOCTORAT ET RECHERCHE
  { value: 'doctorat_droit', label: 'Doctorat en Droit', category: 'superieur_long' },
  { value: 'doctorat_economie', label: 'Doctorat en Économie', category: 'superieur_long' },
  { value: 'doctorat_gestion', label: 'Doctorat en Gestion', category: 'superieur_long' },
  { value: 'doctorat_sciences', label: 'Doctorat en Sciences', category: 'superieur_long' },
  { value: 'doctorat_medecine', label: 'Doctorat en Médecine', category: 'superieur_long' },
  { value: 'doctorat_pharmacie', label: 'Doctorat en Pharmacie', category: 'superieur_long' },
  { value: 'doctorat_odontologie', label: 'Doctorat en Odontologie', category: 'superieur_long' },
  { value: 'doctorat_veterinaire', label: 'Doctorat Vétérinaire', category: 'superieur_long' },
  { value: 'doctorat_lettres', label: 'Doctorat en Lettres', category: 'superieur_long' },
  { value: 'doctorat_langues', label: 'Doctorat en Langues', category: 'superieur_long' },
  { value: 'doctorat_histoire', label: 'Doctorat en Histoire', category: 'superieur_long' },
  { value: 'doctorat_philosophie', label: 'Doctorat en Philosophie', category: 'superieur_long' },
  { value: 'doctorat_education', label: 'Doctorat en Sciences de l\'Éducation', category: 'superieur_long' },
  { value: 'doctorat_psychologie', label: 'Doctorat en Psychologie', category: 'superieur_long' },
  { value: 'doctorat_sociologie', label: 'Doctorat en Sociologie', category: 'superieur_long' },
  { value: 'doctorat_anthropologie', label: 'Doctorat en Anthropologie', category: 'superieur_long' },
  { value: 'doctorat_politique', label: 'Doctorat en Science Politique', category: 'superieur_long' },
  { value: 'doctorat_info_com', label: 'Doctorat en Information-Communication', category: 'superieur_long' },
  { value: 'doctorat_arts', label: 'Doctorat en Arts', category: 'superieur_long' },
  { value: 'doctorat_archi', label: 'Doctorat en Architecture', category: 'superieur_long' },
  { value: 'doctorat_urbanisme', label: 'Doctorat en Urbanisme', category: 'superieur_long' },
  { value: 'doctorat_ingenierie', label: 'Doctorat en Ingénierie', category: 'superieur_long' },
  { value: 'doctorat_informatique', label: 'Doctorat en Informatique', category: 'superieur_long' },
  { value: 'doctorat_mathematiques', label: 'Doctorat en Mathématiques', category: 'superieur_long' },
  { value: 'doctorat_physique', label: 'Doctorat en Physique', category: 'superieur_long' },
  { value: 'doctorat_chimie', label: 'Doctorat en Chimie', category: 'superieur_long' },
  { value: 'doctorat_biologie', label: 'Doctorat en Biologie', category: 'superieur_long' },
  { value: 'doctorat_medecine_pharma', label: 'Doctorat en Sciences Pharmaceutiques', category: 'superieur_long' },
  { value: 'doctorat_sante_publique', label: 'Doctorat en Santé Publique', category: 'superieur_long' },
  { value: 'doctorat_agronomie', label: 'Doctorat en Agronomie', category: 'superieur_long' },
  { value: 'doctorat_environnement', label: 'Doctorat en Environnement', category: 'superieur_long' },
  { value: 'habilitation_diriger_recherches', label: 'HDR', category: 'superieur_long', description: 'Habilitation à Diriger des Recherches' },

  // FORMATIONS MÉDICALES ET PARAMÉDICALES
  { value: 'formation_infirmier', label: 'Formation Infirmier', category: 'superieur_long' },
  { value: 'formation_aide_soignant', label: 'Formation Aide-Soignant', category: 'superieur_long' },
  { value: 'formation_auxiliaire_puériculture', label: 'Formation Auxiliaire de Puériculture', category: 'superieur_long' },
  { value: 'formation_ambulancier', label: 'Formation Ambulancier', category: 'superieur_long' },
  { value: 'formation_kinesitherapeute', label: 'Formation Kinésithérapeute', category: 'superieur_long' },
  { value: 'formation_pedicure_podologue', label: 'Formation Pédicure-Podologue', category: 'superieur_long' },
  { value: 'formation_orthophoniste', label: 'Formation Orthophoniste', category: 'superieur_long' },
  { value: 'formation_orthoptiste', label: 'Formation Orthoptiste', category: 'superieur_long' },
  { value: 'formation_ergotherapeute', label: 'Formation Ergothérapeute', category: 'superieur_long' },
  { value: 'formation_dieteticien', label: 'Formation Diététicien', category: 'superieur_long' },
  { value: 'formation_psychomotricien', label: 'Formation Psychomotricien', category: 'superieur_long' },
  { value: 'formation_manipulateur_radio', label: 'Formation Manipulateur d\'Électroradiologie', category: 'superieur_long' },
  { value: 'formation_preparateur_pharmacie', label: 'Formation Préparateur en Pharmacie', category: 'superieur_long' },
  { value: 'formation_prothesiste_dentaire', label: 'Formation Prothésiste Dentaire', category: 'superieur_long' },
  { value: 'formation_opticien', label: 'Formation Opticien-Lunetier', category: 'superieur_long' },
  { value: 'formation_audioprothesiste', label: 'Formation Audioprothésiste', category: 'superieur_long' },
  { value: 'formation_orthoprothesiste', label: 'Formation Orthoprothésiste', category: 'superieur_long' },
  { value: 'formation_podo_ortheses', label: 'Formation Podo-Orthésiste', category: 'superieur_long' },
  { value: 'formation_technicien_analyses', label: 'Formation Technicien de Laboratoire Médical', category: 'superieur_long' },
  { value: 'formation_technicien_veterinaire', label: 'Formation Auxiliaire Vétérinaire', category: 'superieur_long' },
  { value: 'formation_sage_femme', label: 'Formation Sage-Femme', category: 'superieur_long' },
  { value: 'formation_medecin_generaliste', label: 'DES Médecine Générale', category: 'superieur_long' },
  { value: 'formation_specialite_medicale', label: 'DES Spécialité Médicale', category: 'superieur_long' },
  { value: 'formation_chirurgie', label: 'DESC Chirurgie', category: 'superieur_long' },
  { value: 'formation_anesthesie', label: 'DES Anesthésie-Réanimation', category: 'superieur_long' },
  { value: 'formation_urgences', label: 'DES Urgences', category: 'superieur_long' },
  { value: 'formation_sante_publique', label: 'DES Santé Publique', category: 'superieur_long' },
  { value: 'formation_medecine_travail', label: 'DES Médecine du Travail', category: 'superieur_long' },
  { value: 'formation_medecine_legale', label: 'DES Médecine Légale', category: 'superieur_long' },
  { value: 'formation_genetique_medicale', label: 'DES Génétique Médicale', category: 'superieur_long' },
  { value: 'formation_biologie_medicale', label: 'DES Biologie Médicale', category: 'superieur_long' },
  { value: 'formation_medecine_nucleaire', label: 'DES Médecine Nucléaire', category: 'superieur_long' },
  { value: 'formation_radiotherapie', label: 'DES Radiothérapie', category: 'superieur_long' },
  { value: 'formation_reeducation_readaptation', label: 'DES Rééducation et Réadaptation', category: 'superieur_long' },
  { value: 'formation_psychiatrie', label: 'DES Psychiatrie', category: 'superieur_long' },
  { value: 'formation_pediatrie', label: 'DES Pédiatrie', category: 'superieur_long' },
  { value: 'formation_gynecologie', label: 'DES Gynécologie-Obstétrique', category: 'superieur_long' },
  { value: 'formation_cardiologie', label: 'DES Cardiologie', category: 'superieur_long' },
  { value: 'formation_dermatologie', label: 'DES Dermatologie', category: 'superieur_long' },
  { value: 'formation_endocrinologie', label: 'DES Endocrinologie', category: 'superieur_long' },
  { value: 'formation_gastro_enterologie', label: 'DES Gastro-entérologie', category: 'superieur_long' },
  { value: 'formation_hematologie', label: 'DES Hématologie', category: 'superieur_long' },
  { value: 'formation_hepato_gastro', label: 'DES Hépato-gastro-entérologie', category: 'superieur_long' },
  { value: 'formation_immunologie_clinique', label: 'DES Immunologie Clinique', category: 'superieur_long' },
  { value: 'formation_medecine_interne', label: 'DES Médecine Interne', category: 'superieur_long' },
  { value: 'formation_nephrologie', label: 'DES Néphrologie', category: 'superieur_long' },
  { value: 'formation_neurologie', label: 'DES Neurologie', category: 'superieur_long' },
  { value: 'formation_oncologie', label: 'DES Oncologie', category: 'superieur_long' },
  { value: 'formation_ophtalmologie', label: 'DES Ophtalmologie', category: 'superieur_long' },
  { value: 'formation_orl', label: 'DES ORL', category: 'superieur_long' },
  { value: 'formation_pneumologie', label: 'DES Pneumologie', category: 'superieur_long' },
  { value: 'formation_rhumatologie', label: 'DES Rhumatologie', category: 'superieur_long' },
  { value: 'formation_medecine_sport', label: 'DES Médecine du Sport', category: 'superieur_long' },
  { value: 'formation_chirurgie_generale', label: 'DESC Chirurgie Générale', category: 'superieur_long' },
  { value: 'formation_chirurgie_viscerale', label: 'DESC Chirurgie Visérale', category: 'superieur_long' },
  { value: 'formation_chirurgie_digestive', label: 'DESC Chirurgie Digestive', category: 'superieur_long' },
  { value: 'formation_chirurgie_thoracique', label: 'DESC Chirurgie Thoracique', category: 'superieur_long' },
  { value: 'formation_chirurgie_cardiaque', label: 'DESC Chirurgie Cardiaque', category: 'superieur_long' },
  { value: 'formation_chirurgie_vasculaire', label: 'DESC Chirurgie Vasculaire', category: 'superieur_long' },
  { value: 'formation_neurochirurgie', label: 'DESC Neurochirurgie', category: 'superieur_long' },
  { value: 'formation_chirurgie_orl', label: 'DESC Chirurgie ORL', category: 'superieur_long' },
  { value: 'formation_chirurgie_maxillo', label: 'DESC Chirurgie Maxillo-faciale', category: 'superieur_long' },
  { value: 'formation_chirurgie_plastique', label: 'DESC Chirurgie Plastique', category: 'superieur_long' },
  { value: 'formation_chirurgie_pediatrique', label: 'DESC Chirurgie Pédiatrique', category: 'superieur_long' },
  { value: 'formation_chirurgie_orthopedique', label: 'DESC Chirurgie Orthopédique', category: 'superieur_long' },
  { value: 'formation_chirurgie_urologique', label: 'DESC Chirurgie Urologique', category: 'superieur_long' },
  { value: 'formation_chirurgie_gynecologique', label: 'DESC Chirurgie Gynécologique', category: 'superieur_long' },
  { value: 'formation_chirurgie_orale', label: 'DESC Chirurgie Orale', category: 'superieur_long' },
  { value: 'formation_stomatologie', label: 'DESC Stomatologie', category: 'superieur_long' },
  { value: 'formation_parodontologie', label: 'DESC Parodontologie', category: 'superieur_long' },
  { value: 'formation_prothese_dentaire', label: 'DESC Prothèse Dentaire', category: 'superieur_long' },
  { value: 'formation_orthodontie', label: 'DESC Orthodontie', category: 'superieur_long' },
  { value: 'formation_odonto_pediatrie', label: 'DESC Odontologie Pédiatrique', category: 'superieur_long' },
  { value: 'formation_odonto_conservatrice', label: 'DESC Odontologie Conservatrice', category: 'superieur_long' },
  { value: 'formation_odonto_chirurgicale', label: 'DESC Chirurgie Orale et Implantologie', category: 'superieur_long' },
  { value: 'formation_medecine_buccale', label: 'DESC Médecine Buccale', category: 'superieur_long' },
  { value: 'formation_radio_medecine_nucleaire', label: 'DESC Radiologie et Médecine Nucléaire', category: 'superieur_long' },
  { value: 'formation_medecine_physique', label: 'DESC Médecine Physique et Réadaptation', category: 'superieur_long' },
  { value: 'formation_sante_environnement', label: 'DES Santé Environnement', category: 'superieur_long' },
  { value: 'formation_addictologie', label: 'DES Addictologie', category: 'superieur_long' },
  { value: 'formation_allergologie', label: 'DES Allergologie', category: 'superieur_long' },
  { value: 'formation_medecine_urgence', label: 'DES Médecine d\'Urgence', category: 'superieur_long' },
  { value: 'formation_medecine_vasculaire', label: 'DES Médecine Vasculaire', category: 'superieur_long' },
  { value: 'formation_nutrition', label: 'DES Nutrition', category: 'superieur_long' },
  { value: 'formation_onco_hematologie', label: 'DES Onco-Hématologie', category: 'superieur_long' },
  { value: 'formation_palliatifs', label: 'DES Soins Palliatifs', category: 'superieur_long' },
  { value: 'formation_pediatrie_neonatologie', label: 'DES Pédiatrie-Néonatologie', category: 'superieur_long' },
  { value: 'formation_pharmacie_clinique', label: 'DES Pharmacie Clinique', category: 'superieur_long' },
  { value: 'formation_pharmacie_hospitaliere', label: 'DES Pharmacie Hospitalière', category: 'superieur_long' },
  { value: 'formation_pharmacie_biologie', label: 'DES Pharmacie-Biologie', category: 'superieur_long' },
  { value: 'formation_pharmacie_industrielle', label: 'DES Pharmacie Industrielle', category: 'superieur_long' },
  { value: 'formation_pharmacie_officine', label: 'DES Pharmacie d\'Officine', category: 'superieur_long' },
  { value: 'formation_sante_publique_med', label: 'DES Santé Publique', category: 'superieur_long' },
  { value: 'formation_medecine_ipe', label: 'DES Médecine IPE', category: 'superieur_long', description: 'Innovation, Pharmacologie, Épidémiologie' },
]

// Fonction utilitaire pour récupérer les filières par catégorie
export function getFilieresByCategory(categoryId: string): Filiere[] {
  return FILIERES.filter(filiere => filiere.category === categoryId)
}

// Fonction pour rechercher des filières
export function searchFilieres(query: string): Filiere[] {
  const lowercaseQuery = query.toLowerCase()
  return FILIERES.filter(filiere => 
    filiere.label.toLowerCase().includes(lowercaseQuery) ||
    filiere.description?.toLowerCase().includes(lowercaseQuery) ||
    filiere.value.toLowerCase().includes(lowercaseQuery)
  )
}

// Fonction pour obtenir le label d'une filière par sa valeur
export function getFiliereLabel(value: string): string {
  const filiere = FILIERES.find(f => f.value === value)
  return filiere?.label || value
}

// Fonction pour obtenir la catégorie d'une filière
export function getFiliereCategory(value: string): string {
  const filiere = FILIERES.find(f => f.value === value)
  return filiere?.category || 'unknown'
}

// Fonction pour obtenir le nombre de filières par catégorie
export function getFilieresCountByCategory(): Record<string, number> {
  return CATEGORIES.reduce((acc, category) => {
    acc[category.id] = FILIERES.filter(f => f.category === category.id).length
    return acc
  }, {} as Record<string, number>)
}
